### ISSUE TITLE
Harmonogram

### ISSUE THREAD

**Issue by schab** [schab/calcSheets#1]
Plan na cały tydzień:

Lena Sieradzka, Aleksander Karżanowski : :+1: Utworzenie szablonu interfejsu aplikacji przedstawionego w formie pliku o formacie .PNG  

Bartosz Zabielski, Kacper Sobisz, Hubert Święcioch : :8ball: Spisanie wymagań funkcjonalnych i niefunkcjonalnych do pliku tekstowego o formacie .docx.

Przewidywany czas zakończenia wyznaczonych zadań:
Utworzenie szablonu: :date:  17 marzec 2015 rok
Sporządzenie specyfikacji wymagań: :date: 17 marzec 2015 rok

**Comment by hubertSwiecioch** [comment]
Proszę nie używać formatu .docx
